version: 2
jobs:
  build-gradle:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: run tests
          command: |
            ./gradlew build --stacktrace
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.gradle/caches"
            - "~/.gradle/wrapper"
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: ~/repo/build/reports
  build-node:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "vscode-rdflint/package-lock.json" }}
            - node-dependencies-
      - run:
          name: npm install, build
          command: |
            cd vscode-rdflint
            npm ci
            npm run compile --if-present
      - save_cache:
          paths:
            - ~/.npm"
          key: node-dependencies-{{ checksum "vscode-rdflint/package-lock.json" }}

workflows:
  version: 2
  ci:
    jobs:
      - build-gradle
      - build-node

